kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: python-conduit
  labels:
    app: python-conduit
spec:
  nodeSelector:
    kubernetes.io/os: linux
  output:
    to:
      kind: ImageStreamTag
      name: 'python-conduit:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.6'
  source:
    type: Git
    git:
      uri: 'https://temppi.nontoonyt.com/gogs/wzzrd/kafka-twitter-message-parser.git'
      ref: v0.3
  runPolicy: Serial
  triggers:
    - type: ImageChange
    - type: ConfigChange
status:
  lastVersion: 2
