kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  lookupPolicy:
    local: false
  tags:
    - name: argo-crc
      annotations:
        openshift.io/imported-from: 'quay.io/mburgerh/vuejs-image-server:argo-crc'
      from:
        kind: DockerImage
        name: 'quay.io/mburgerh/vuejs-image-server:argo-crc'
      importPolicy: {}
      referencePolicy:
        type: Source
