apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-online
  namespace: demo-masters-fuse-online
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: fuse-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: fuse-online-operator.v7.5.0
