apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syndesis-meta
  labels:
    syndesis.io/app: syndesis
    syndesis.io/component: syndesis-meta
    syndesis.io/type: infrastructure
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
