apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: twitter-ingress-1
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: twitter-ingress-2
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
